#ifndef HEADFILE_H
#define HEADFILE_H

#include "CLCAAddress.h"
#include "CLCAAddressIPV4.h"
#include "CLCAClientContext.h"
#include "CLCAClientPostNetMsgBySocket.h"
#include "CLCADeSerializer.h"
#include "CLCAGETPKMessage.h"
#include "CLCAGETPKMsgDeSerializer.h"
#include "CLCAGETPKMsgSerializer.h"
#include "CLCAGETPKMutiMsgDeSerializer.h"
#include "CLCAGETPKMutiMsgSerializer.h"
#include "CLCAMessage.h"
#include "CLCAPostNetMsgTool.h"
#include "CLCASerializer.h"
#include "CLCAServer.h"
#include "CLCAServerByEpoll.h"
#include "CLCAServerManager.h"
#include "CLCAServerManager.h"
#include "CLDataReceviver.h"
#include "CLDataReceviverBySocket.h"
#include "CLEpoll.h"
#include "CLMessageObserver.h"
#include "CLProtocolDecapsulator.h"
#include "CLServerMessageObserver.h"
#include "CLSocket.h"
#include "CLCAREGETPKMessage.h"
#include "CLCAREGETPKMsgSerializer.h"
#include "CLCAREGETPKMsgDeSerializer.h"

#endif